-- Jamaican Jobs Database Seeder
-- This script populates the companies and jobs tables with realistic Jamaican job market data
-- Includes diverse industries, parishes, and salary ranges in JMD

-- Clear existing data
DELETE FROM jobs;
DELETE FROM companies;

-- Insert companies first
INSERT INTO companies (id, name, description, location, industry, website) VALUES
('comp_1', 'DigiTech Solutions JA', 'Leading technology solutions provider in Jamaica', 'New Kingston', 'Technology', 'https://digitech.com.jm'),
('comp_2', 'WebCraft Jamaica', 'Creative web development agency', 'Half Way Tree', 'Technology', 'https://webcraft.jm'),
('comp_3', 'Jamaica Business Solutions', 'Comprehensive IT support services', 'Spanish Town', 'Technology', 'https://jbs.com.jm'),
('comp_4', 'Kingston Public Hospital', 'Premier healthcare institution', 'Kingston', 'Healthcare', 'https://kph.gov.jm'),
('comp_5', 'Mandeville Medical Centre', 'Modern medical facility', 'Mandeville', 'Healthcare', 'https://mmc.com.jm'),
('comp_6', 'National Commercial Bank', 'Leading financial institution', 'New Kingston', 'Finance', 'https://ncb.com'),
('comp_7', 'Scotiabank Jamaica', 'International banking services', 'Montego Bay', 'Finance', 'https://scotiabank.com.jm'),
('comp_8', 'Meadowbrook Preparatory School', 'Quality primary education', 'Meadowbrook', 'Education', 'https://meadowbrook.edu.jm'),
('comp_9', 'Academic Excellence Centre', 'Tutoring and test preparation', 'Liguanea', 'Education', 'https://academic-excellence.jm'),
('comp_10', 'Sandals Montego Bay', 'Luxury resort and hospitality', 'Montego Bay', 'Tourism', 'https://sandals.com'),
('comp_11', 'Island Adventures Tours', 'Authentic Jamaican tour experiences', 'Ocho Rios', 'Tourism', 'https://island-adventures.jm'),
('comp_12', 'Ministry of Agriculture', 'Government agricultural services', 'May Pen', 'Agriculture', 'https://moa.gov.jm'),
('comp_13', 'Grace Foods Jamaica', 'Food processing and manufacturing', 'Spanish Town', 'Manufacturing', 'https://gracefoods.com'),
('comp_14', 'Digicel Jamaica', 'Telecommunications leader', 'Kingston', 'Telecommunications', 'https://digicel.com'),
('comp_15', 'Courts Jamaica', 'Retail and furniture', 'Portmore', 'Retail', 'https://courts.com.jm'),
('comp_16', 'Caribbean Engineering Solutions', 'Civil engineering and construction', 'Kingston', 'Construction', 'https://ces.com.jm'),
('comp_17', 'FLOW Jamaica', 'Cable and internet services', 'New Kingston', 'Telecommunications', 'https://discoverflow.co'),
('comp_18', 'Red Stripe Jamaica', 'Brewing and beverages', 'Kingston', 'Manufacturing', 'https://redstripe.com'),
('comp_19', 'Guardian Security Services', 'Professional security solutions', 'Spanish Town', 'Security', 'https://guardian-security.jm'),
('comp_20', 'Jamaica Post', 'National postal service', 'Kingston', 'Transportation', 'https://jamaicapost.gov.jm'),
('comp_21', 'Campbell & Associates', 'Legal services and consultation', 'New Kingston', 'Legal', 'https://campbell-law.jm'),
('comp_22', 'Caribbean Content Creators', 'Digital content and marketing', 'Remote', 'Marketing', 'https://caribbean-content.com'),
('comp_23', 'Global VA Solutions', 'Virtual assistant services', 'Remote', 'Administrative', 'https://global-va.com');

-- Insert jobs
INSERT INTO jobs (id, company_id, title, description, location, type, salary, skills, education, experience, status) VALUES 

-- Technology & IT Jobs
('job_1', 'comp_1', 'Senior Software Developer', 
'Join our dynamic tech team to build innovative solutions for the Caribbean market. Work with modern technologies including React, Node.js, and cloud platforms.',
'DigiTech Solutions JA', 
'New Kingston', 
'Kingston', 
4500000, 
6000000, 
'FULL_TIME', 
'SENIOR', 
'Technology', 
'["JavaScript", "React", "Node.js", "AWS", "MongoDB", "Git"]',
'Bachelor''s degree in Computer Science or related field. 5+ years experience in full-stack development. Strong problem-solving skills.',
'["Health insurance", "Flexible working hours", "Professional development budget", "Remote work options"]',
true, 
'MEDIUM', 
CURRENT_DATE - INTERVAL ''3 days'', 
CURRENT_DATE + INTERVAL ''25 days'',
true),

('Junior Web Developer',
'Perfect opportunity for a recent graduate to start their career in web development. You''ll work on exciting projects for local businesses and gain valuable experience.',
'WebCraft Jamaica',
'Half Way Tree',
'Kingston',
2400000,
3200000,
'FULL_TIME',
'ENTRY_LEVEL',
'Technology',
'["HTML", "CSS", "JavaScript", "PHP", "MySQL", "WordPress"]',
'Diploma or degree in Computer Science, Web Development, or related field. Basic knowledge of web technologies. Eager to learn and grow.',
'["Training programs", "Mentorship", "Health insurance", "Career advancement opportunities"]',
false,
'SMALL',
CURRENT_DATE - INTERVAL '1 day',
CURRENT_DATE + INTERVAL '20 days',
true),

('IT Support Specialist',
'Provide technical support to our growing organization. Troubleshoot hardware and software issues, maintain network infrastructure, and support end users.',
'Jamaica Business Solutions',
'Spanish Town',
'St. Catherine',
2800000,
3600000,
'FULL_TIME',
'MID_LEVEL',
'Technology',
'["Windows", "Network Administration", "Hardware Troubleshooting", "Microsoft Office", "Active Directory"]',
'Associate degree in IT or equivalent experience. 2-3 years in technical support. Strong communication skills.',
'["Health and dental insurance", "Paid training", "Equipment allowance"]',
false,
'LARGE',
CURRENT_DATE - INTERVAL '5 days',
CURRENT_DATE + INTERVAL '15 days',
true),

-- Healthcare Jobs
('Registered Nurse',
'Join our compassionate healthcare team providing quality patient care. Work in a modern facility with opportunities for professional growth.',
'Kingston Public Hospital',
'Kingston',
'Kingston',
3200000,
4200000,
'FULL_TIME',
'MID_LEVEL',
'Healthcare',
'["Patient Care", "Medical Records", "CPR Certified", "Medication Administration", "Emergency Response"]',
'Valid nursing license in Jamaica. 2+ years clinical experience preferred. BLS certification required.',
'["Comprehensive health insurance", "Pension plan", "Continuing education support", "Shift differentials"]',
false,
'LARGE',
CURRENT_DATE - INTERVAL '7 days',
CURRENT_DATE + INTERVAL '30 days',
true),

('Medical Receptionist',
'Front desk position at busy medical practice. Handle patient scheduling, insurance verification, and administrative duties.',
'Mandeville Medical Centre',
'Mandeville',
'Manchester',
2000000,
2600000,
'FULL_TIME',
'ENTRY_LEVEL',
'Healthcare',
'["Customer Service", "Medical Terminology", "Appointment Scheduling", "Insurance Processing", "Phone Etiquette"]',
'High school diploma required. Previous medical office experience preferred. Strong organizational skills.',
'["Health insurance", "Paid vacation", "Professional development"]',
false,
'MEDIUM',
CURRENT_DATE - INTERVAL '2 days',
CURRENT_DATE + INTERVAL '14 days',
true),

-- Finance & Banking
('Financial Analyst',
'Analyze financial data, prepare reports, and support strategic decision-making for one of Jamaica''s leading financial institutions.',
'National Commercial Bank',
'New Kingston',
'Kingston',
3800000,
5200000,
'FULL_TIME',
'MID_LEVEL',
'Finance',
'["Financial Analysis", "Excel", "Financial Modeling", "Risk Assessment", "Report Writing", "PowerBI"]',
'Bachelor''s degree in Finance, Accounting, or Economics. 3+ years experience in financial analysis. Strong analytical skills.',
'["Competitive salary", "Performance bonuses", "Health insurance", "Pension plan", "Professional certifications"]',
false,
'LARGE',
CURRENT_DATE - INTERVAL '4 days',
CURRENT_DATE + INTERVAL '21 days',
true),

('Bank Teller',
'Provide excellent customer service while handling daily banking transactions. Great opportunity to start a career in banking.',
'Scotiabank Jamaica',
'Montego Bay',
'St. James',
2200000,
2800000,
'FULL_TIME',
'ENTRY_LEVEL',
'Finance',
'["Customer Service", "Cash Handling", "Attention to Detail", "Banking Software", "Communication"]',
'High school diploma required. Previous customer service experience preferred. Must pass background check.',
'["Health insurance", "Banking benefits", "Career advancement", "Training programs"]',
false,
'LARGE',
CURRENT_DATE - INTERVAL '1 day',
CURRENT_DATE + INTERVAL '18 days',
true),

-- Education
('Primary School Teacher',
'Teach and inspire young minds in grades 1-6. Create engaging lesson plans and foster a positive learning environment.',
'Meadowbrook Preparatory School',
'Meadowbrook',
'Kingston',
2600000,
3400000,
'FULL_TIME',
'MID_LEVEL',
'Education',
'["Classroom Management", "Curriculum Development", "Child Psychology", "Educational Technology", "Assessment"]',
'Bachelor''s degree in Education or teaching certificate. 2+ years teaching experience. Passion for working with children.',
'["Summer vacation", "Health insurance", "Professional development", "Pension plan"]',
false,
'MEDIUM',
CURRENT_DATE - INTERVAL '6 days',
CURRENT_DATE + INTERVAL '28 days',
true),

('Mathematics Tutor',
'Provide one-on-one and small group tutoring for high school students preparing for CSEC and CAPE examinations.',
'Academic Excellence Centre',
'Liguanea',
'Kingston',
150000,
300000,
'PART_TIME',
'MID_LEVEL',
'Education',
'["Mathematics", "CSEC Preparation", "CAPE Preparation", "Tutoring", "Student Assessment"]',
'Bachelor''s degree in Mathematics or related field. Experience with CSEC/CAPE curriculum. Excellent communication skills.',
'["Flexible schedule", "Performance bonuses", "Professional development"]',
false,
'SMALL',
CURRENT_DATE - INTERVAL '3 days',
CURRENT_DATE + INTERVAL '12 days',
true),

-- Tourism & Hospitality
('Hotel Manager',
'Oversee daily operations of our luxury resort property. Ensure exceptional guest experiences and manage staff across all departments.',
'Sandals Montego Bay',
'Montego Bay',
'St. James',
4200000,
6000000,
'FULL_TIME',
'SENIOR',
'Tourism',
'["Hotel Management", "Staff Leadership", "Customer Service", "Budget Management", "Operations", "Hospitality"]',
'Bachelor''s degree in Hospitality Management or related field. 5+ years hotel management experience. Strong leadership skills.',
'["Competitive salary", "Resort benefits", "Health insurance", "Performance bonuses", "Travel perks"]',
false,
'LARGE',
CURRENT_DATE - INTERVAL '8 days',
CURRENT_DATE + INTERVAL '35 days',
true),

('Tour Guide',
'Lead exciting tours showcasing Jamaica''s natural beauty and rich culture. Share your knowledge and passion for our beautiful island.',
'Island Adventures Tours',
'Ocho Rios',
'St. Ann',
1800000,
2400000,
'FULL_TIME',
'ENTRY_LEVEL',
'Tourism',
'["Public Speaking", "Jamaican History", "Customer Service", "First Aid", "Languages", "Cultural Knowledge"]',
'High school diploma. Knowledge of Jamaican history and culture. Excellent communication skills. First Aid certification preferred.',
'["Tips", "Travel opportunities", "Health insurance", "Flexible schedule"]',
false,
'MEDIUM',
CURRENT_DATE - INTERVAL '2 days',
CURRENT_DATE + INTERVAL '16 days',
true),

-- Agriculture
('Agricultural Extension Officer',
'Support local farmers with modern farming techniques, crop management, and sustainable agriculture practices.',
'Ministry of Agriculture',
'May Pen',
'Clarendon',
2800000,
3600000,
'FULL_TIME',
'MID_LEVEL',
'Agriculture',
'["Crop Management", "Soil Science", "Pest Control", "Sustainable Agriculture", "Farmer Education", "Data Collection"]',
'Bachelor''s degree in Agriculture or related field. 2+ years field experience. Valid driver''s license required.',
'["Government benefits", "Pension plan", "Health insurance", "Vehicle allowance", "Professional development"]',
false,
'GOVERNMENT',
CURRENT_DATE - INTERVAL '5 days',
CURRENT_DATE + INTERVAL '22 days',
true),

-- Manufacturing
('Production Supervisor',
'Supervise manufacturing operations, ensure quality standards, and lead production teams in our food processing facility.',
'Grace Foods Jamaica',
'Spanish Town',
'St. Catherine',
3400000,
4400000,
'FULL_TIME',
'SENIOR',
'Manufacturing',
'["Production Management", "Quality Control", "Team Leadership", "Safety Protocols", "Lean Manufacturing", "Food Safety"]',
'Bachelor''s degree in Engineering or related field. 4+ years manufacturing experience. Strong leadership skills.',
'["Competitive salary", "Health insurance", "Performance bonuses", "Safety training", "Career advancement"]',
false,
'LARGE',
CURRENT_DATE - INTERVAL '4 days',
CURRENT_DATE + INTERVAL '19 days',
true),

-- Retail & Sales
('Sales Representative',
'Drive sales growth by building relationships with clients and promoting our telecommunications services across the island.',
'Digicel Jamaica',
'Kingston',
'Kingston',
2600000,
3800000,
'FULL_TIME',
'MID_LEVEL',
'Sales',
'["Sales", "Customer Relationship Management", "Telecommunications", "Negotiation", "Territory Management", "CRM Software"]',
'Bachelor''s degree preferred. 2+ years sales experience. Valid driver''s license. Strong communication skills.',
'["Commission structure", "Company car", "Health insurance", "Performance bonuses", "Travel allowance"]',
false,
'LARGE',
CURRENT_DATE - INTERVAL '3 days',
CURRENT_DATE + INTERVAL '17 days',
true),

('Store Manager',
'Manage daily operations of our retail location, supervise staff, and ensure excellent customer service.',
'Courts Jamaica',
'Portmore',
'St. Catherine',
3000000,
4000000,
'FULL_TIME',
'SENIOR',
'Retail',
'["Retail Management", "Staff Supervision", "Inventory Management", "Customer Service", "Sales Analysis", "Visual Merchandising"]',
'Bachelor''s degree in Business or related field. 3+ years retail management experience. Strong leadership skills.',
'["Employee discounts", "Health insurance", "Performance bonuses", "Career development", "Pension plan"]',
false,
'LARGE',
CURRENT_DATE - INTERVAL '6 days',
CURRENT_DATE + INTERVAL '24 days',
true),

-- Construction
('Civil Engineer',
'Design and oversee construction projects including roads, bridges, and infrastructure developments across Jamaica.',
'Caribbean Engineering Solutions',
'Kingston',
'Kingston',
4000000,
5500000,
'FULL_TIME',
'SENIOR',
'Construction',
'["Civil Engineering", "AutoCAD", "Project Management", "Structural Design", "Construction Management", "Site Supervision"]',
'Bachelor''s degree in Civil Engineering. Professional Engineer license preferred. 4+ years experience in construction projects.',
'["Competitive salary", "Project bonuses", "Health insurance", "Professional development", "Equipment allowance"]',
false,
'MEDIUM',
CURRENT_DATE - INTERVAL '7 days',
CURRENT_DATE + INTERVAL '26 days',
true),

-- Customer Service
('Customer Service Representative',
'Provide exceptional customer support via phone, email, and chat for our telecommunications services.',
'FLOW Jamaica',
'New Kingston',
'Kingston',
2200000,
2800000,
'FULL_TIME',
'ENTRY_LEVEL',
'Customer Service',
'["Customer Service", "Phone Support", "Problem Solving", "Computer Skills", "Communication", "Multitasking"]',
'High school diploma required. Previous customer service experience preferred. Strong communication skills.',
'["Health insurance", "Performance bonuses", "Career advancement", "Training programs", "Flexible schedule"]',
true,
'LARGE',
CURRENT_DATE - INTERVAL '1 day',
CURRENT_DATE + INTERVAL '13 days',
true),

-- Marketing
('Digital Marketing Specialist',
'Develop and execute digital marketing campaigns across social media, email, and web platforms to grow our brand presence.',
'Red Stripe Jamaica',
'Kingston',
'Kingston',
3200000,
4200000,
'FULL_TIME',
'MID_LEVEL',
'Marketing',
'["Digital Marketing", "Social Media", "Google Analytics", "Content Creation", "SEO", "Email Marketing", "Adobe Creative Suite"]',
'Bachelor''s degree in Marketing or related field. 2+ years digital marketing experience. Strong creative skills.',
'["Creative environment", "Health insurance", "Performance bonuses", "Professional development", "Company events"]',
false,
'LARGE',
CURRENT_DATE - INTERVAL '4 days',
CURRENT_DATE + INTERVAL '20 days',
true),

-- Security
('Security Guard',
'Provide security services for commercial properties, monitor premises, and ensure safety of personnel and assets.',
'Guardian Security Services',
'Spanish Town',
'St. Catherine',
1800000,
2200000,
'FULL_TIME',
'ENTRY_LEVEL',
'Security',
'["Security Procedures", "Surveillance", "Report Writing", "Emergency Response", "Customer Service", "Physical Fitness"]',
'High school diploma. Security license required. Previous security experience preferred. Clean background check.',
'["Uniform provided", "Health insurance", "Overtime opportunities", "Training programs"]',
false,
'MEDIUM',
CURRENT_DATE - INTERVAL '2 days',
CURRENT_DATE + INTERVAL '15 days',
true),

-- Transportation
('Delivery Driver',
'Deliver packages and goods across the Kingston Metropolitan Area. Excellent opportunity for reliable, customer-focused individuals.',
'Jamaica Post',
'Kingston',
'Kingston',
2000000,
2600000,
'FULL_TIME',
'ENTRY_LEVEL',
'Transportation',
'["Driving", "Customer Service", "Time Management", "Route Planning", "Package Handling", "GPS Navigation"]',
'Valid driver''s license with clean record. High school diploma. Previous delivery experience preferred.',
'["Vehicle provided", "Fuel allowance", "Health insurance", "Overtime pay", "Pension plan"]',
false,
'GOVERNMENT',
CURRENT_DATE - INTERVAL '3 days',
CURRENT_DATE + INTERVAL '18 days',
true),

-- Legal
('Legal Assistant',
'Support attorneys with legal research, document preparation, and client communication in our busy law practice.',
'Campbell & Associates',
'New Kingston',
'Kingston',
2800000,
3600000,
'FULL_TIME',
'MID_LEVEL',
'Legal',
'["Legal Research", "Document Preparation", "Client Communication", "Case Management", "Legal Writing", "Court Procedures"]',
'Associate degree in Legal Studies or Paralegal certificate. 2+ years legal experience. Strong attention to detail.',
'["Professional environment", "Health insurance", "Continuing education", "Performance bonuses"]',
false,
'SMALL',
CURRENT_DATE - INTERVAL '5 days',
CURRENT_DATE + INTERVAL '23 days',
true),

-- Remote Work Opportunities
('Content Writer',
'Create engaging content for websites, blogs, and social media platforms. Work remotely while contributing to exciting projects.',
'Caribbean Content Creators',
'Remote',
'All Parishes',
2400000,
3600000,
'FULL_TIME',
'MID_LEVEL',
'Marketing',
'["Content Writing", "SEO Writing", "Social Media", "Research", "Editing", "WordPress", "Content Strategy"]',
'Bachelor''s degree in English, Journalism, or related field. 2+ years writing experience. Strong portfolio required.',
'["Remote work", "Flexible hours", "Health insurance", "Professional development", "Performance bonuses"]',
true,
'SMALL',
CURRENT_DATE - INTERVAL '2 days',
CURRENT_DATE + INTERVAL '21 days',
true),

('Virtual Assistant',
'Provide administrative support to international clients from the comfort of your home. Flexible schedule available.',
'Global VA Solutions',
'Remote',
'All Parishes',
1800000,
2800000,
'PART_TIME',
'ENTRY_LEVEL',
'Administrative',
'["Administrative Support", "Email Management", "Scheduling", "Data Entry", "Customer Service", "Microsoft Office"]',
'High school diploma. Strong computer skills. Reliable internet connection. Previous administrative experience preferred.',
'["Remote work", "Flexible schedule", "Performance bonuses", "Training provided"]',
true,
'SMALL',
CURRENT_DATE - INTERVAL '1 day',
CURRENT_DATE + INTERVAL '14 days',
true);

-- Update statistics
SELECT 'Jobs seeded successfully!' as message;
SELECT COUNT(*) as total_jobs FROM jobs;
SELECT industry, COUNT(*) as job_count FROM jobs GROUP BY industry ORDER BY job_count DESC;
SELECT parish, COUNT(*) as job_count FROM jobs GROUP BY parish ORDER BY job_count DESC;
