# Update from Node 16 to Node 18 LTS
FROM node:18.19.0

WORKDIR /app

COPY web-frontend/package*.json ./

# Install dependencies with support for resolutions and legacy peer deps
RUN npm install --legacy-peer-deps --install-links

# No need for separate react-icons install as it's in package.json

COPY web-frontend/ .

CMD ["npm", "start"]
