FROM node:16.20.0

WORKDIR /app

COPY web-frontend/package*.json ./
RUN npm install --legacy-peer-deps
RUN npm install react-icons@4.10.1 --save --legacy-peer-deps

COPY web-frontend/ .

CMD ["npm", "start"]
