# docker-compose.yml

version: '3.8'

services:
  # MongoDB - replacement for DynamoDB in local environment
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=jobboard
      - MONGO_INITDB_ROOT_PASSWORD=jobboard
    volumes:
      - ./mongodb:/data/db

  # Express API Server - running backend code locally
  api:
    build:
      context: ..
      dockerfile: Dockerfile.api
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - MONGO_URI=mongodb://jobboard:jobboard@mongodb:27017/jobboard?authSource=admin
      - JWT_SECRET=local_development_secret
      - NODE_ENV=development
      - AWS_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
    volumes:
      - api_node_modules:/app/node_modules
      - ../backend/server.js:/app/server.js:delegated
      - ../backend/package.json:/app/package.json:delegated
      - ../backend/package-lock.json:/app/package-lock.json:delegated
      - uploads:/app/uploads
    depends_on:
      - mongodb

  # Frontend development server  
  frontend:
    build:
      context: ..
      dockerfile: Dockerfile.frontend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:5000
      - REACT_APP_ENVIRONMENT=local
      - WDS_SOCKET_PORT=0
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ../web-frontend:/app
      - frontend_node_modules:/app/node_modules
      # Add public directory mount for images
      - ../web-frontend/public:/app/public
    command: >
      sh -c "cd /app && 
             npm install react-icons --save && 
             npm start"
    depends_on:
      - api

volumes:
  api_node_modules:
  frontend_node_modules:
  uploads:
